version: "3"

tasks:
  genereer-vera-bvg-modellen:
    desc: Genereer VERA BVG modellen
    cmds:
      - |
        datamodel-codegen \
          --url https://raw.githubusercontent.com/Aedes-datastandaarden/vera-openapi/main/docs/Ketenprocessen/BVG.yaml \
          --input-file-type openapi \
          --output woningwaardering/vera/bvg/generated.py \
          --output-model-type pydantic_v2.BaseModel \
          --use-standard-collections \
          --use-default-kwarg \
          --target-python-version 3.10 \
          --use-field-description \
          --use-schema-description \
          --snake-case-field \
          --disable-timestamp \
          --enum-field-as-literal one \
          --use-double-quotes \
          --field-constraints \
          --allow-population-by-field-name \
          --strict-nullable \
          --use-title-as-name
      - python scripts/uitbreiden_vera_modellen.py
  genereer-vera-referentiedata:
    desc: Genereer VERA referentiedata
    cmds:
      - python scripts/genereer_vera_referentiedata.py
  genereer-opzet-woningwaarderinggroep:
    desc: Genereer de opzet voor de code van een woningwaarderinggroep
    cmds:
      - python scripts/genereer_opzet_woningwaarderinggroep.py
