
from woningwaardering.vera.referentiedata.soort import AUTHENTIEKGEGEVENBRON, EENHEIDKLIMAATBEHEERSINGSOORT, RUIMTESOORT, WONINGWAARDERINGSTELSEL


class :
    AUTHENTIEKGEGEVENBRON = AUTHENTIEKGEGEVENBRON.AUTHENTIEKGEGEVENBRON

    EENHEIDKLIMAATBEHEERSINGSOORT = EENHEIDKLIMAATBEHEERSINGSOORT.EENHEIDKLIMAATBEHEERSINGSOORT

    RUIMTESOORT = RUIMTESOORT.RUIMTESOORT

    WONINGWAARDERINGSTELSEL = WONINGWAARDERINGSTELSEL.WONINGWAARDERINGSTELSEL
