
from woningwaardering.vera.referentiedata.soort import AUTHENTIEKGEGEVENBRON, AUTHENTIEKGEGEVENSOORT, AUTHENTIEKGEGEVENSTATUS, INFORMATIEOBJECTDETAILSOORT, INFORMATIEOBJECTSOORT, VERTROUWELIJKHEID, ZAAKOBJECTSOORT, ZAAKROL, ZAAKSTATUSSOORT, ZAAKTYPEDETAILSOORT, ZAAKTYPESOORT


class Dossier:
    AUTHENTIEKGEGEVENBRON = AUTHENTIEKGEGEVENBRON.AUTHENTIEKGEGEVENBRON

    AUTHENTIEKGEGEVENSOORT = AUTHENTIEKGEGEVENSOORT.AUTHENTIEKGEGEVENSOORT

    AUTHENTIEKGEGEVENSTATUS = AUTHENTIEKGEGEVENSTATUS.AUTHENTIEKGEGEVENSTATUS

    INFORMATIEOBJECTDETAILSOORT = INFORMATIEOBJECTDETAILSOORT.INFORMATIEOBJECTDETAILSOORT

    INFORMATIEOBJECTSOORT = INFORMATIEOBJECTSOORT.INFORMATIEOBJECTSOORT

    VERTROUWELIJKHEID = VERTROUWELIJKHEID.VERTROUWELIJKHEID

    ZAAKOBJECTSOORT = ZAAKOBJECTSOORT.ZAAKOBJECTSOORT

    ZAAKROL = ZAAKROL.ZAAKROL

    ZAAKSTATUSSOORT = ZAAKSTATUSSOORT.ZAAKSTATUSSOORT

    ZAAKTYPEDETAILSOORT = ZAAKTYPEDETAILSOORT.ZAAKTYPEDETAILSOORT

    ZAAKTYPESOORT = ZAAKTYPESOORT.ZAAKTYPESOORT
