from woningwaardering.vera.referentiedata.soort import (
    ENERGIEPRESTATIESOORT,
    ENERGIEPRESTATIESTATUS,
    ENERGIEPRESTATIEVERGOEDINGSOORT,
)


class Energie:
    ENERGIEPRESTATIESOORT = ENERGIEPRESTATIESOORT.ENERGIEPRESTATIESOORT

    ENERGIEPRESTATIESTATUS = ENERGIEPRESTATIESTATUS.ENERGIEPRESTATIESTATUS

    ENERGIEPRESTATIEVERGOEDINGSOORT = (
        ENERGIEPRESTATIEVERGOEDINGSOORT.ENERGIEPRESTATIEVERGOEDINGSOORT
    )
