from woningwaardering.vera.referentiedata.soort import (
    BEDRIJFSOORT,
    BEGROTINGVERSIE,
    BETAALWIJZEDEELSOORT,
    BETAALWIJZESOORT,
    BETALINGSREGELINGEINDEREDEN,
    BETALINGSREGELINGSTATUS,
    BOEKINGDETAILSOORT,
    BOEKINGSOORT,
    BOEKINGSTATUS,
    BOEKJAARPERIODESOORT,
    BOEKJAARPERIODESTATUS,
    BOEKJAARSTATUS,
    BTWAANGIFTESTATUS,
    CREDITEURSOORT,
    CREDITEURSTATUS,
    DEBITEURSOORT,
    DEBITEURSTATUS,
    EXTERNEINCASSOSOORT,
    EXTERNEINCASSOSTATUS,
    FACTUURBETAALWIJZE,
    FACTUURSOORT,
    GROOTBOEKMUTATIEHERKOMST,
    GROOTBOEKREKENINGSOORT,
    GROOTBOEKREKENINGSTATUS,
    INKOOPFACTUURSTATUS,
    INKOOPOPDRACHTREGELSOORT,
    LENINGAFLOSVORM,
    LENINGDETAILSOORT,
    LENINGSOORT,
    MAATSCHAPPELIJKLABEL,
    MACHTIGINGSOORT,
    MEETEENHEID,
    PRIJSAANPASSINGSOORT,
    RENTESOORT,
    VERANTWOORDINGCONSOLIDATIE,
    VERANTWOORDINGREGIME,
    VERBIJZONDERINGSOORT,
    VERBIJZONDERINGSTATUS,
)


class Financien:
    BEDRIJFSOORT = BEDRIJFSOORT.BEDRIJFSOORT

    BEGROTINGVERSIE = BEGROTINGVERSIE.BEGROTINGVERSIE

    BETAALWIJZEDEELSOORT = BETAALWIJZEDEELSOORT.BETAALWIJZEDEELSOORT

    BETAALWIJZESOORT = BETAALWIJZESOORT.BETAALWIJZESOORT

    BETALINGSREGELINGEINDEREDEN = (
        BETALINGSREGELINGEINDEREDEN.BETALINGSREGELINGEINDEREDEN
    )

    BETALINGSREGELINGSTATUS = BETALINGSREGELINGSTATUS.BETALINGSREGELINGSTATUS

    BOEKINGDETAILSOORT = BOEKINGDETAILSOORT.BOEKINGDETAILSOORT

    BOEKINGSOORT = BOEKINGSOORT.BOEKINGSOORT

    BOEKINGSTATUS = BOEKINGSTATUS.BOEKINGSTATUS

    BOEKJAARPERIODESOORT = BOEKJAARPERIODESOORT.BOEKJAARPERIODESOORT

    BOEKJAARPERIODESTATUS = BOEKJAARPERIODESTATUS.BOEKJAARPERIODESTATUS

    BOEKJAARSTATUS = BOEKJAARSTATUS.BOEKJAARSTATUS

    BTWAANGIFTESTATUS = BTWAANGIFTESTATUS.BTWAANGIFTESTATUS

    CREDITEURSOORT = CREDITEURSOORT.CREDITEURSOORT

    CREDITEURSTATUS = CREDITEURSTATUS.CREDITEURSTATUS

    DEBITEURSOORT = DEBITEURSOORT.DEBITEURSOORT

    DEBITEURSTATUS = DEBITEURSTATUS.DEBITEURSTATUS

    EXTERNEINCASSOSOORT = EXTERNEINCASSOSOORT.EXTERNEINCASSOSOORT

    EXTERNEINCASSOSTATUS = EXTERNEINCASSOSTATUS.EXTERNEINCASSOSTATUS

    FACTUURBETAALWIJZE = FACTUURBETAALWIJZE.FACTUURBETAALWIJZE

    FACTUURSOORT = FACTUURSOORT.FACTUURSOORT

    GROOTBOEKMUTATIEHERKOMST = GROOTBOEKMUTATIEHERKOMST.GROOTBOEKMUTATIEHERKOMST

    GROOTBOEKREKENINGSOORT = GROOTBOEKREKENINGSOORT.GROOTBOEKREKENINGSOORT

    GROOTBOEKREKENINGSTATUS = GROOTBOEKREKENINGSTATUS.GROOTBOEKREKENINGSTATUS

    INKOOPFACTUURSTATUS = INKOOPFACTUURSTATUS.INKOOPFACTUURSTATUS

    INKOOPOPDRACHTREGELSOORT = INKOOPOPDRACHTREGELSOORT.INKOOPOPDRACHTREGELSOORT

    LENINGAFLOSVORM = LENINGAFLOSVORM.LENINGAFLOSVORM

    LENINGDETAILSOORT = LENINGDETAILSOORT.LENINGDETAILSOORT

    LENINGSOORT = LENINGSOORT.LENINGSOORT

    MAATSCHAPPELIJKLABEL = MAATSCHAPPELIJKLABEL.MAATSCHAPPELIJKLABEL

    MACHTIGINGSOORT = MACHTIGINGSOORT.MACHTIGINGSOORT

    MEETEENHEID = MEETEENHEID.MEETEENHEID

    PRIJSAANPASSINGSOORT = PRIJSAANPASSINGSOORT.PRIJSAANPASSINGSOORT

    RENTESOORT = RENTESOORT.RENTESOORT

    VERANTWOORDINGCONSOLIDATIE = VERANTWOORDINGCONSOLIDATIE.VERANTWOORDINGCONSOLIDATIE

    VERANTWOORDINGREGIME = VERANTWOORDINGREGIME.VERANTWOORDINGREGIME

    VERBIJZONDERINGSOORT = VERBIJZONDERINGSOORT.VERBIJZONDERINGSOORT

    VERBIJZONDERINGSTATUS = VERBIJZONDERINGSTATUS.VERBIJZONDERINGSTATUS
