from woningwaardering.vera.referentiedata.soort import (
    AFREKENWIJZESOORT,
    DEFECTLOCATIE,
    DEFECTOORZAAK,
    DEFECTSOORT,
    DEFECTSTATUS,
    INSPECTIERAPPORTSOORT,
    INSPECTIERAPPORTSTATUS,
    ONDERHOUDSBESTEDINGSOORT,
    ONDERHOUDSOORT,
    ONDERHOUDSORDERSTATUS,
    ONDERHOUDSPECIALISME,
    ONDERHOUDSTAAKDETAILSTATUS,
    ONDERHOUDSTAAKSTATUS,
    ONDERHOUDSVERZOEKSTATUS,
    UITVOERENDESOORT,
    VERREKENINGSOORT,
)


class Onderhoud:
    AFREKENWIJZESOORT = AFREKENWIJZESOORT.AFREKENWIJZESOORT

    DEFECTLOCATIE = DEFECTLOCATIE.DEFECTLOCATIE

    DEFECTOORZAAK = DEFECTOORZAAK.DEFECTOORZAAK

    DEFECTSOORT = DEFECTSOORT.DEFECTSOORT

    DEFECTSTATUS = DEFECTSTATUS.DEFECTSTATUS

    INSPECTIERAPPORTSOORT = INSPECTIERAPPORTSOORT.INSPECTIERAPPORTSOORT

    INSPECTIERAPPORTSTATUS = INSPECTIERAPPORTSTATUS.INSPECTIERAPPORTSTATUS

    ONDERHOUDSBESTEDINGSOORT = ONDERHOUDSBESTEDINGSOORT.ONDERHOUDSBESTEDINGSOORT

    ONDERHOUDSOORT = ONDERHOUDSOORT.ONDERHOUDSOORT

    ONDERHOUDSORDERSTATUS = ONDERHOUDSORDERSTATUS.ONDERHOUDSORDERSTATUS

    ONDERHOUDSPECIALISME = ONDERHOUDSPECIALISME.ONDERHOUDSPECIALISME

    ONDERHOUDSTAAKDETAILSTATUS = ONDERHOUDSTAAKDETAILSTATUS.ONDERHOUDSTAAKDETAILSTATUS

    ONDERHOUDSTAAKSTATUS = ONDERHOUDSTAAKSTATUS.ONDERHOUDSTAAKSTATUS

    ONDERHOUDSVERZOEKSTATUS = ONDERHOUDSVERZOEKSTATUS.ONDERHOUDSVERZOEKSTATUS

    UITVOERENDESOORT = UITVOERENDESOORT.UITVOERENDESOORT

    VERREKENINGSOORT = VERREKENINGSOORT.VERREKENINGSOORT
