
from woningwaardering.vera.referentiedata.soort import AFWEZIGHEIDSOORT, MEDEWERKERROL, MEDEWERKERSOORT


class Organisatie:
    AFWEZIGHEIDSOORT = AFWEZIGHEIDSOORT.AFWEZIGHEIDSOORT

    MEDEWERKERROL = MEDEWERKERROL.MEDEWERKERROL

    MEDEWERKERSOORT = MEDEWERKERSOORT.MEDEWERKERSOORT
