from woningwaardering.vera.referentiedata.soort import (
    BTW,
    EINDEDETAILREDEN,
    EINDEREDEN,
    HUURGESCHILSOORT,
    HUURGESCHILSTATUS,
    HUUROPZEGGINGSTATUS,
    INCASSOMOMENT,
    INSCHRIJVINGHERKOMST,
    MAATSCHAPPELIJKLABEL,
    OPZEGTERMIJN,
    OVEREENKOMSTDETAILSOORT,
    OVEREENKOMSTKOPPELINGDETAILSTATUS,
    OVEREENKOMSTKOPPELINGSTATUS,
    OVEREENKOMSTSOORT,
    OVEREENKOMSTSTATUS,
    PRIJSCOMPONENTDETAILSOORT,
    PRIJSCOMPONENTSOORT,
    PRIJSCOMPONENTSUBSIDIESOORT,
    PRIJSCOMPONENTWIJZIGINGSREDEN,
    REDENONTBINDING,
    REDENOPZEGGING,
    REDENVERNIETIGING,
)


class Overeenkomsten:
    BTW = BTW.BTW

    EINDEDETAILREDEN = EINDEDETAILREDEN.EINDEDETAILREDEN

    EINDEREDEN = EINDEREDEN.EINDEREDEN

    HUURGESCHILSOORT = HUURGESCHILSOORT.HUURGESCHILSOORT

    HUURGESCHILSTATUS = HUURGESCHILSTATUS.HUURGESCHILSTATUS

    HUUROPZEGGINGSTATUS = HUUROPZEGGINGSTATUS.HUUROPZEGGINGSTATUS

    INCASSOMOMENT = INCASSOMOMENT.INCASSOMOMENT

    INSCHRIJVINGHERKOMST = INSCHRIJVINGHERKOMST.INSCHRIJVINGHERKOMST

    MAATSCHAPPELIJKLABEL = MAATSCHAPPELIJKLABEL.MAATSCHAPPELIJKLABEL

    OPZEGTERMIJN = OPZEGTERMIJN.OPZEGTERMIJN

    OVEREENKOMSTDETAILSOORT = OVEREENKOMSTDETAILSOORT.OVEREENKOMSTDETAILSOORT

    OVEREENKOMSTKOPPELINGDETAILSTATUS = (
        OVEREENKOMSTKOPPELINGDETAILSTATUS.OVEREENKOMSTKOPPELINGDETAILSTATUS
    )

    OVEREENKOMSTKOPPELINGSTATUS = (
        OVEREENKOMSTKOPPELINGSTATUS.OVEREENKOMSTKOPPELINGSTATUS
    )

    OVEREENKOMSTSOORT = OVEREENKOMSTSOORT.OVEREENKOMSTSOORT

    OVEREENKOMSTSTATUS = OVEREENKOMSTSTATUS.OVEREENKOMSTSTATUS

    PRIJSCOMPONENTDETAILSOORT = PRIJSCOMPONENTDETAILSOORT.PRIJSCOMPONENTDETAILSOORT

    PRIJSCOMPONENTSOORT = PRIJSCOMPONENTSOORT.PRIJSCOMPONENTSOORT

    PRIJSCOMPONENTSUBSIDIESOORT = (
        PRIJSCOMPONENTSUBSIDIESOORT.PRIJSCOMPONENTSUBSIDIESOORT
    )

    PRIJSCOMPONENTWIJZIGINGSREDEN = (
        PRIJSCOMPONENTWIJZIGINGSREDEN.PRIJSCOMPONENTWIJZIGINGSREDEN
    )

    REDENONTBINDING = REDENONTBINDING.REDENONTBINDING

    REDENOPZEGGING = REDENOPZEGGING.REDENOPZEGGING

    REDENVERNIETIGING = REDENVERNIETIGING.REDENVERNIETIGING
