
from woningwaardering.vera.referentiedata.soort import PROJECTBUDGETREGELREGELSOORT, PROJECTBUDGETREGELSOORT, PROJECTBUDGETREGELSTATUS, PROJECTFASEBESLUITSTATUS, PROJECTSOORT, PROJECTSTATUS, REGIESOORT


class Projectontwikkeling:
    PROJECTBUDGETREGELREGELSOORT = PROJECTBUDGETREGELREGELSOORT.PROJECTBUDGETREGELREGELSOORT

    PROJECTBUDGETREGELSOORT = PROJECTBUDGETREGELSOORT.PROJECTBUDGETREGELSOORT

    PROJECTBUDGETREGELSTATUS = PROJECTBUDGETREGELSTATUS.PROJECTBUDGETREGELSTATUS

    PROJECTFASEBESLUITSTATUS = PROJECTFASEBESLUITSTATUS.PROJECTFASEBESLUITSTATUS

    PROJECTSOORT = PROJECTSOORT.PROJECTSOORT

    PROJECTSTATUS = PROJECTSTATUS.PROJECTSTATUS

    REGIESOORT = REGIESOORT.REGIESOORT
