
from woningwaardering.vera.referentiedata.soort import ACCOUNTSTATUS, ADRESSOORT, AFSPRAAKSTATUS, AFSPRAAKVERZOEKSOORT, BETAALGEGEVENSOORT, BURGERLIJKESTAAT, COMMUNICATIEKANAAL, COMMUNICATIERICHTING, CONTACTGEGEVENDETAILSOORT, CONTACTGEGEVENSOORT, CONTACTGEGEVENSTATUS, CONTACTGEGEVENVOORKEUR, DAGDEEL, GESLACHT, INKOMENSBRON, INKOMENSSOORT, INKOMENSVERKLARINGSOORT, OPLEIDINGSNIVEAU, ORGANISATIEVORM, RELATIEADRESSOORT, RELATIEDETAILSOORT, RELATIEROLSOORT, RELATIESOORT, RELATIESTATUS, SIGNALERINGDETAILSOORT, SIGNALERINGSOORT, SIGNALERINGSTATUS


class Relaties:
    ACCOUNTSTATUS = ACCOUNTSTATUS.ACCOUNTSTATUS

    ADRESSOORT = ADRESSOORT.ADRESSOORT

    AFSPRAAKSTATUS = AFSPRAAKSTATUS.AFSPRAAKSTATUS

    AFSPRAAKVERZOEKSOORT = AFSPRAAKVERZOEKSOORT.AFSPRAAKVERZOEKSOORT

    BETAALGEGEVENSOORT = BETAALGEGEVENSOORT.BETAALGEGEVENSOORT

    BURGERLIJKESTAAT = BURGERLIJKESTAAT.BURGERLIJKESTAAT

    COMMUNICATIEKANAAL = COMMUNICATIEKANAAL.COMMUNICATIEKANAAL

    COMMUNICATIERICHTING = COMMUNICATIERICHTING.COMMUNICATIERICHTING

    CONTACTGEGEVENDETAILSOORT = CONTACTGEGEVENDETAILSOORT.CONTACTGEGEVENDETAILSOORT

    CONTACTGEGEVENSOORT = CONTACTGEGEVENSOORT.CONTACTGEGEVENSOORT

    CONTACTGEGEVENSTATUS = CONTACTGEGEVENSTATUS.CONTACTGEGEVENSTATUS

    CONTACTGEGEVENVOORKEUR = CONTACTGEGEVENVOORKEUR.CONTACTGEGEVENVOORKEUR

    DAGDEEL = DAGDEEL.DAGDEEL

    GESLACHT = GESLACHT.GESLACHT

    INKOMENSBRON = INKOMENSBRON.INKOMENSBRON

    INKOMENSSOORT = INKOMENSSOORT.INKOMENSSOORT

    INKOMENSVERKLARINGSOORT = INKOMENSVERKLARINGSOORT.INKOMENSVERKLARINGSOORT

    OPLEIDINGSNIVEAU = OPLEIDINGSNIVEAU.OPLEIDINGSNIVEAU

    ORGANISATIEVORM = ORGANISATIEVORM.ORGANISATIEVORM

    RELATIEADRESSOORT = RELATIEADRESSOORT.RELATIEADRESSOORT

    RELATIEDETAILSOORT = RELATIEDETAILSOORT.RELATIEDETAILSOORT

    RELATIEROLSOORT = RELATIEROLSOORT.RELATIEROLSOORT

    RELATIESOORT = RELATIESOORT.RELATIESOORT

    RELATIESTATUS = RELATIESTATUS.RELATIESTATUS

    SIGNALERINGDETAILSOORT = SIGNALERINGDETAILSOORT.SIGNALERINGDETAILSOORT

    SIGNALERINGSOORT = SIGNALERINGSOORT.SIGNALERINGSOORT

    SIGNALERINGSTATUS = SIGNALERINGSTATUS.SIGNALERINGSTATUS
