from woningwaardering.vera.referentiedata.soort import (
    AANVULLENDEDOELGROEP,
    AKTESOORT,
    BESTEMMING,
    BOUWKUNDIGELEMENTDETAILSOORT,
    BOUWKUNDIGELEMENTPLAATSING,
    BOUWKUNDIGELEMENTSOORT,
    BRANDWERENDHEIDSCORE,
    CLUSTERSOORT,
    COLLECTIEFOBJECTSOORT,
    CONDITIESCORE,
    DOELGROEP,
    EENHEIDCRITERIASOORT,
    EENHEIDCRITERIUMTOEPASSING,
    EENHEIDDETAILSOORT,
    EENHEIDDETAILSTATUS,
    EENHEIDENERGIEVOORZIENING,
    EENHEIDINTERIEUR,
    EENHEIDISOLATIE,
    EENHEIDKLIMAATBEHEERSING,
    EENHEIDKLIMAATBEHEERSINGSOORT,
    EENHEIDLIGGING,
    EENHEIDMONUMENT,
    EENHEIDPRIJSCONDITIE,
    EENHEIDSANITAIR,
    EENHEIDSOORT,
    EENHEIDSTATUS,
    ENERGIELABEL,
    GEOMETRIESOORT,
    HUURKLASSE,
    INEXPLOITATIEREDEN,
    KWALITEITSNIVEAU,
    MAATSCHAPPELIJKLABEL,
    MATERIAALDETAILSOORT,
    MATERIAALSOORT,
    ONDERHOUDSLABEL,
    OPPERVLAKTESOORT,
    PRESTATIEAFSPRAAK,
    PROVINCIE,
    RUIMTEDETAILSOORT,
    RUIMTELIGGING,
    RUIMTESOORT,
    TOEGANKELIJKHEIDSLABEL,
    UITEXPLOITATIEREDEN,
    WONINGWAARDERINGSTELSEL,
    WONINGWAARDERINGSTELSELGROEP,
    WOONVORM,
    ZEKERHEIDVERPANDINGSOORT,
)


class Vastgoed:
    AANVULLENDEDOELGROEP = AANVULLENDEDOELGROEP.AANVULLENDEDOELGROEP

    AKTESOORT = AKTESOORT.AKTESOORT

    BESTEMMING = BESTEMMING.BESTEMMING

    BOUWKUNDIGELEMENTDETAILSOORT = (
        BOUWKUNDIGELEMENTDETAILSOORT.BOUWKUNDIGELEMENTDETAILSOORT
    )

    BOUWKUNDIGELEMENTPLAATSING = BOUWKUNDIGELEMENTPLAATSING.BOUWKUNDIGELEMENTPLAATSING

    BOUWKUNDIGELEMENTSOORT = BOUWKUNDIGELEMENTSOORT.BOUWKUNDIGELEMENTSOORT

    BRANDWERENDHEIDSCORE = BRANDWERENDHEIDSCORE.BRANDWERENDHEIDSCORE

    CLUSTERSOORT = CLUSTERSOORT.CLUSTERSOORT

    COLLECTIEFOBJECTSOORT = COLLECTIEFOBJECTSOORT.COLLECTIEFOBJECTSOORT

    CONDITIESCORE = CONDITIESCORE.CONDITIESCORE

    DOELGROEP = DOELGROEP.DOELGROEP

    EENHEIDCRITERIASOORT = EENHEIDCRITERIASOORT.EENHEIDCRITERIASOORT

    EENHEIDCRITERIUMTOEPASSING = EENHEIDCRITERIUMTOEPASSING.EENHEIDCRITERIUMTOEPASSING

    EENHEIDDETAILSOORT = EENHEIDDETAILSOORT.EENHEIDDETAILSOORT

    EENHEIDDETAILSTATUS = EENHEIDDETAILSTATUS.EENHEIDDETAILSTATUS

    EENHEIDENERGIEVOORZIENING = EENHEIDENERGIEVOORZIENING.EENHEIDENERGIEVOORZIENING

    EENHEIDINTERIEUR = EENHEIDINTERIEUR.EENHEIDINTERIEUR

    EENHEIDISOLATIE = EENHEIDISOLATIE.EENHEIDISOLATIE

    EENHEIDKLIMAATBEHEERSING = EENHEIDKLIMAATBEHEERSING.EENHEIDKLIMAATBEHEERSING

    EENHEIDKLIMAATBEHEERSINGSOORT = (
        EENHEIDKLIMAATBEHEERSINGSOORT.EENHEIDKLIMAATBEHEERSINGSOORT
    )

    EENHEIDLIGGING = EENHEIDLIGGING.EENHEIDLIGGING

    EENHEIDMONUMENT = EENHEIDMONUMENT.EENHEIDMONUMENT

    EENHEIDPRIJSCONDITIE = EENHEIDPRIJSCONDITIE.EENHEIDPRIJSCONDITIE

    EENHEIDSANITAIR = EENHEIDSANITAIR.EENHEIDSANITAIR

    EENHEIDSOORT = EENHEIDSOORT.EENHEIDSOORT

    EENHEIDSTATUS = EENHEIDSTATUS.EENHEIDSTATUS

    ENERGIELABEL = ENERGIELABEL.ENERGIELABEL

    GEOMETRIESOORT = GEOMETRIESOORT.GEOMETRIESOORT

    HUURKLASSE = HUURKLASSE.HUURKLASSE

    INEXPLOITATIEREDEN = INEXPLOITATIEREDEN.INEXPLOITATIEREDEN

    KWALITEITSNIVEAU = KWALITEITSNIVEAU.KWALITEITSNIVEAU

    MAATSCHAPPELIJKLABEL = MAATSCHAPPELIJKLABEL.MAATSCHAPPELIJKLABEL

    MATERIAALDETAILSOORT = MATERIAALDETAILSOORT.MATERIAALDETAILSOORT

    MATERIAALSOORT = MATERIAALSOORT.MATERIAALSOORT

    ONDERHOUDSLABEL = ONDERHOUDSLABEL.ONDERHOUDSLABEL

    OPPERVLAKTESOORT = OPPERVLAKTESOORT.OPPERVLAKTESOORT

    PRESTATIEAFSPRAAK = PRESTATIEAFSPRAAK.PRESTATIEAFSPRAAK

    PROVINCIE = PROVINCIE.PROVINCIE

    RUIMTEDETAILSOORT = RUIMTEDETAILSOORT.RUIMTEDETAILSOORT

    RUIMTELIGGING = RUIMTELIGGING.RUIMTELIGGING

    RUIMTESOORT = RUIMTESOORT.RUIMTESOORT

    TOEGANKELIJKHEIDSLABEL = TOEGANKELIJKHEIDSLABEL.TOEGANKELIJKHEIDSLABEL

    UITEXPLOITATIEREDEN = UITEXPLOITATIEREDEN.UITEXPLOITATIEREDEN

    WONINGWAARDERINGSTELSEL = WONINGWAARDERINGSTELSEL.WONINGWAARDERINGSTELSEL

    WONINGWAARDERINGSTELSELGROEP = (
        WONINGWAARDERINGSTELSELGROEP.WONINGWAARDERINGSTELSELGROEP
    )

    WOONVORM = WOONVORM.WOONVORM

    ZEKERHEIDVERPANDINGSOORT = ZEKERHEIDVERPANDINGSOORT.ZEKERHEIDVERPANDINGSOORT
