from woningwaardering.vera.referentiedata.soort import (
    AANBIEDINGDETAILSTATUS,
    AANBIEDINGSTATUS,
    AANVULLENDEDOELGROEP,
    DOELGROEP,
    EENHEIDCRITERIUMDETAILSOORT,
    EENHEIDCRITERIUMSOORT,
    GEBEURTENISSOORT,
    KANDIDAATDETAILSTATUS,
    KANDIDAATSTATUS,
    PASSENDHEIDDETAILSOORT,
    PASSENDHEIDSSOORT,
    PUBLICATIEDETAILMODEL,
    PUBLICATIEDETAILSTATUS,
    PUBLICATIEINTAKEVORM,
    PUBLICATIEMODEL,
    PUBLICATIESTATUS,
    PUNTENBEREKENINGSOORT,
    PUNTENMUTATIESOORT,
    RECLAMATIESOORT,
    RECLAMATIESTATUS,
    SANCTIESOORT,
    SANCTIESTATUS,
    TAAL,
    VOORRANGDETAILSOORT,
    VOORRANGSOORT,
    WOONSITUATIESOORT,
)


class Woonruimteverdeling:
    AANBIEDINGDETAILSTATUS = AANBIEDINGDETAILSTATUS.AANBIEDINGDETAILSTATUS

    AANBIEDINGSTATUS = AANBIEDINGSTATUS.AANBIEDINGSTATUS

    AANVULLENDEDOELGROEP = AANVULLENDEDOELGROEP.AANVULLENDEDOELGROEP

    DOELGROEP = DOELGROEP.DOELGROEP

    EENHEIDCRITERIUMDETAILSOORT = (
        EENHEIDCRITERIUMDETAILSOORT.EENHEIDCRITERIUMDETAILSOORT
    )

    EENHEIDCRITERIUMSOORT = EENHEIDCRITERIUMSOORT.EENHEIDCRITERIUMSOORT

    GEBEURTENISSOORT = GEBEURTENISSOORT.GEBEURTENISSOORT

    KANDIDAATDETAILSTATUS = KANDIDAATDETAILSTATUS.KANDIDAATDETAILSTATUS

    KANDIDAATSTATUS = KANDIDAATSTATUS.KANDIDAATSTATUS

    PASSENDHEIDDETAILSOORT = PASSENDHEIDDETAILSOORT.PASSENDHEIDDETAILSOORT

    PASSENDHEIDSSOORT = PASSENDHEIDSSOORT.PASSENDHEIDSSOORT

    PUBLICATIEDETAILMODEL = PUBLICATIEDETAILMODEL.PUBLICATIEDETAILMODEL

    PUBLICATIEDETAILSTATUS = PUBLICATIEDETAILSTATUS.PUBLICATIEDETAILSTATUS

    PUBLICATIEINTAKEVORM = PUBLICATIEINTAKEVORM.PUBLICATIEINTAKEVORM

    PUBLICATIEMODEL = PUBLICATIEMODEL.PUBLICATIEMODEL

    PUBLICATIESTATUS = PUBLICATIESTATUS.PUBLICATIESTATUS

    PUNTENBEREKENINGSOORT = PUNTENBEREKENINGSOORT.PUNTENBEREKENINGSOORT

    PUNTENMUTATIESOORT = PUNTENMUTATIESOORT.PUNTENMUTATIESOORT

    RECLAMATIESOORT = RECLAMATIESOORT.RECLAMATIESOORT

    RECLAMATIESTATUS = RECLAMATIESTATUS.RECLAMATIESTATUS

    SANCTIESOORT = SANCTIESOORT.SANCTIESOORT

    SANCTIESTATUS = SANCTIESTATUS.SANCTIESTATUS

    TAAL = TAAL.TAAL

    VOORRANGDETAILSOORT = VOORRANGDETAILSOORT.VOORRANGDETAILSOORT

    VOORRANGSOORT = VOORRANGSOORT.VOORRANGSOORT

    WOONSITUATIESOORT = WOONSITUATIESOORT.WOONSITUATIESOORT
