# coding: utf-8

"""
    VERA-Beheer Vastgoedgegevens

    API-specificatie van ketenproces 'Beheer Vastgoedgegevens'. Deze specificatie is gebaseerd op VERA versie 4.1.4+240311.2

    The version of the OpenAPI document: 1.1.4+240311.2
    Contact: VERA@aedesdatastandaarden.nl
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
from pydantic import BaseModel, ConfigDict, Field, ValidationError, field_validator
from typing import Any, List, Optional
from woningwaardering.vera.bvg.models.clusters_natuurlijk_persoon import (
    ClustersNatuurlijkPersoon,
)
from woningwaardering.vera.bvg.models.clusters_rechtspersoon import (
    ClustersRechtspersoon,
)
from typing import Union, Dict
from typing_extensions import Literal, Self

CLUSTERSRELATIE_ONE_OF_SCHEMAS = ["ClustersNatuurlijkPersoon", "ClustersRechtspersoon"]


class ClustersRelatie(BaseModel):
    """
    ClustersRelatie
    """

    # data type: ClustersNatuurlijkPersoon
    oneof_schema_1_validator: Optional[ClustersNatuurlijkPersoon] = None
    # data type: ClustersRechtspersoon
    oneof_schema_2_validator: Optional[ClustersRechtspersoon] = None
    actual_instance: Optional[
        Union[ClustersNatuurlijkPersoon, ClustersRechtspersoon]
    ] = None
    one_of_schemas: List[str] = Field(
        default=Literal["ClustersNatuurlijkPersoon", "ClustersRechtspersoon"]
    )

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError(
                    "If a position argument is used, only 1 is allowed to set `actual_instance`"
                )
            if kwargs:
                raise ValueError(
                    "If a position argument is used, keyword arguments cannot be used."
                )
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator("actual_instance")
    def actual_instance_must_validate_oneof(cls, v):
        error_messages = []
        match = 0
        # validate data type: ClustersNatuurlijkPersoon
        if not isinstance(v, ClustersNatuurlijkPersoon):
            error_messages.append(
                f"Error! Input type `{type(v)}` is not `ClustersNatuurlijkPersoon`"
            )
        else:
            match += 1
        # validate data type: ClustersRechtspersoon
        if not isinstance(v, ClustersRechtspersoon):
            error_messages.append(
                f"Error! Input type `{type(v)}` is not `ClustersRechtspersoon`"
            )
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError(
                "Multiple matches found when setting `actual_instance` in ClustersRelatie with oneOf schemas: ClustersNatuurlijkPersoon, ClustersRechtspersoon. Details: "
                + ", ".join(error_messages)
            )
        elif match == 0:
            # no match
            raise ValueError(
                "No match found when setting `actual_instance` in ClustersRelatie with oneOf schemas: ClustersNatuurlijkPersoon, ClustersRechtspersoon. Details: "
                + ", ".join(error_messages)
            )
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into ClustersNatuurlijkPersoon
        try:
            instance.actual_instance = ClustersNatuurlijkPersoon.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into ClustersRechtspersoon
        try:
            instance.actual_instance = ClustersRechtspersoon.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError(
                "Multiple matches found when deserializing the JSON string into ClustersRelatie with oneOf schemas: ClustersNatuurlijkPersoon, ClustersRechtspersoon. Details: "
                + ", ".join(error_messages)
            )
        elif match == 0:
            # no match
            raise ValueError(
                "No match found when deserializing the JSON string into ClustersRelatie with oneOf schemas: ClustersNatuurlijkPersoon, ClustersRechtspersoon. Details: "
                + ", ".join(error_messages)
            )
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(
            self.actual_instance.to_json
        ):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(
        self,
    ) -> Optional[
        Union[Dict[str, Any], ClustersNatuurlijkPersoon, ClustersRechtspersoon]
    ]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(
            self.actual_instance.to_dict
        ):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())
