# coding: utf-8

"""
    VERA-Beheer Vastgoedgegevens

    API-specificatie van ketenproces 'Beheer Vastgoedgegevens'. Deze specificatie is gebaseerd op VERA versie 4.1.4+240311.2

    The version of the OpenAPI document: 1.1.4+240311.2
    Contact: VERA@aedesdatastandaarden.nl
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from woningwaardering.vera.bvg.models.eenheden_marktwaarde import EenhedenMarktwaarde
from typing import Set
from typing_extensions import Self


class EenhedenBeleidswaarde(BaseModel):
    """
    EenhedenBeleidswaarde
    """  # noqa: E501

    id: Optional[StrictStr] = Field(
        default=None,
        description="De primaire sleutel van het gegeven in het bronsysteem. Je verstuurt een entiteit altijd met het eigen id. Id kan leeg zijn.",
    )
    id_extern: Optional[StrictStr] = Field(
        default=None,
        description="De primaire sleutel van het gegeven in het doelsysteem. Deze idExtern wisselt om met id afhankelijk van de richting van de gegevensuitwisseling.",
        alias="idExtern",
    )
    id_gegevensbeheerder: Optional[StrictStr] = Field(
        default=None,
        description="De primaire sleutel van het gegeven van de gegevensbeheerder. Bijv. de overheid of andere standaarden.",
        alias="idGegevensbeheerder",
    )
    id_organisatie: Optional[StrictStr] = Field(
        default=None,
        description="Dit verwijst naar de organisatie die verantwoordelijk is voor het gegeven. Horende bij de idExtern.",
        alias="idOrganisatie",
    )
    id_administratie: Optional[StrictStr] = Field(
        default=None,
        description="Dit verwijst naar de administratie waar het gegeven onderdeel van is. Horende bij de idExtern.",
        alias="idAdministratie",
    )
    code: Optional[StrictStr] = Field(
        default=None,
        description="De unieke code (Bijvoorbeeld om te tonen of te zoeken)",
    )
    achterstallig_onderhoud: Optional[Union[StrictFloat, StrictInt]] = Field(
        default=None,
        description="Bedrag aan achterstallig onderhoud dat als correctie is toegepast.",
        alias="achterstalligOnderhoud",
    )
    afkoop_erfpacht: Optional[Union[StrictFloat, StrictInt]] = Field(
        default=None,
        description="Het bedrag aan afkoop erfpacht dat als correctie is toegepast.",
        alias="afkoopErfpacht",
    )
    beheer_afslag: Optional[Union[StrictFloat, StrictInt]] = Field(
        default=None,
        description="Beheer (beheer): eventuele extra beheeruitgaven die gepaard gaan met de sociale doelgroep.",
        alias="beheerAfslag",
    )
    beheerskosten: Optional[Union[StrictFloat, StrictInt]] = Field(
        default=None,
        description="Beheerkosten op het moment van waarderen zoals toegepast in de beleidswaardeberekening.",
    )
    beschikbaarheid_afslag: Optional[Union[StrictFloat, StrictInt]] = Field(
        default=None,
        description="Beschikbaarheid (doorexploiteren): in stand houden van een sociale portefeuille.",
        alias="beschikbaarheidAfslag",
    )
    betaalbaarheid_afslag: Optional[Union[StrictFloat, StrictInt]] = Field(
        default=None,
        description="Betaalbaarheid (huur): in stand houden van sociale huurprijzen passend bij de doelgroep.",
        alias="betaalbaarheidAfslag",
    )
    kwaliteit_afslag: Optional[Union[StrictFloat, StrictInt]] = Field(
        default=None,
        description="Kwaliteit (onderhoud): eventuele extra onderhoudsuitgaven voor het op lange termijn in stand houden van de portefeuille.",
        alias="kwaliteitAfslag",
    )
    marktwaarde: Optional[EenhedenMarktwaarde] = Field(
        default=None,
        description="De verwijzing naar de marktwaarde die ten grondslag ligt aan deze beleidswaarde.",
    )
    onderhoudskosten: Optional[Union[StrictFloat, StrictInt]] = Field(
        default=None,
        description="Onderhoudskosten op het moment van waarderen zoals toegepast in de beleidswaardeberekening.",
    )
    streefhuur: Optional[Union[StrictFloat, StrictInt]] = Field(
        default=None,
        description="Actuele streefhuur op het moment van waarderen zoals toegepast in de beleidswaardeberekening.",
    )
    waarde: Optional[Union[StrictFloat, StrictInt]] = Field(
        default=None,
        description="De beleidswaarde van de eenheid waarde die rekening houdt met het beleid van de corporatie. Marktwaarde minus de afslagen voor beschikbaarheid, betaalbaarheid, kwaliteit en beheer, vormt de beleidswaarde (bron beleidswaarde WSW). Let op: het verslagjaar waarvoor de beleidswaarde is bepaald is het verslagjaar van de marktwaarde die de grondslag vormt van de beleidswaarde.",
    )
    __properties: ClassVar[List[str]] = [
        "id",
        "idExtern",
        "idGegevensbeheerder",
        "idOrganisatie",
        "idAdministratie",
        "code",
        "achterstalligOnderhoud",
        "afkoopErfpacht",
        "beheerAfslag",
        "beheerskosten",
        "beschikbaarheidAfslag",
        "betaalbaarheidAfslag",
        "kwaliteitAfslag",
        "marktwaarde",
        "onderhoudskosten",
        "streefhuur",
        "waarde",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of EenhedenBeleidswaarde from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of marktwaarde
        if self.marktwaarde:
            _dict["marktwaarde"] = self.marktwaarde.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of EenhedenBeleidswaarde from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "id": obj.get("id"),
                "idExtern": obj.get("idExtern"),
                "idGegevensbeheerder": obj.get("idGegevensbeheerder"),
                "idOrganisatie": obj.get("idOrganisatie"),
                "idAdministratie": obj.get("idAdministratie"),
                "code": obj.get("code"),
                "achterstalligOnderhoud": obj.get("achterstalligOnderhoud"),
                "afkoopErfpacht": obj.get("afkoopErfpacht"),
                "beheerAfslag": obj.get("beheerAfslag"),
                "beheerskosten": obj.get("beheerskosten"),
                "beschikbaarheidAfslag": obj.get("beschikbaarheidAfslag"),
                "betaalbaarheidAfslag": obj.get("betaalbaarheidAfslag"),
                "kwaliteitAfslag": obj.get("kwaliteitAfslag"),
                "marktwaarde": EenhedenMarktwaarde.from_dict(obj["marktwaarde"])
                if obj.get("marktwaarde") is not None
                else None,
                "onderhoudskosten": obj.get("onderhoudskosten"),
                "streefhuur": obj.get("streefhuur"),
                "waarde": obj.get("waarde"),
            }
        )
        return _obj
