# coding: utf-8

"""
    VERA-Beheer Vastgoedgegevens

    API-specificatie van ketenproces 'Beheer Vastgoedgegevens'. Deze specificatie is gebaseerd op VERA versie 4.1.4+240311.2

    The version of the OpenAPI document: 1.1.4+240311.2
    Contact: VERA@aedesdatastandaarden.nl
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field
from woningwaardering.vera.bvg.models.referentiedata import Referentiedata

class EenhedenGeometrieBasis(BaseModel):
    """
    EenhedenGeometrieBasis
    """
    soort: Optional[Referentiedata] = Field(None, description="soort Geometrie: punt of omtrek Referentiedatasoort GEOMETRIESOORT.")
    __properties = ["soort"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> EenhedenGeometrieBasis:
        """Create an instance of EenhedenGeometrieBasis from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of soort
        if self.soort:
            _dict['soort'] = self.soort.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> EenhedenGeometrieBasis:
        """Create an instance of EenhedenGeometrieBasis from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return EenhedenGeometrieBasis.parse_obj(obj)

        _obj = EenhedenGeometrieBasis.parse_obj({
            "soort": Referentiedata.from_dict(obj.get("soort")) if obj.get("soort") is not None else None
        })
        return _obj


