# coding: utf-8

"""
    VERA-Beheer Vastgoedgegevens

    API-specificatie van ketenproces 'Beheer Vastgoedgegevens'. Deze specificatie is gebaseerd op VERA versie 4.1.4+240311.2

    The version of the OpenAPI document: 1.1.4+240311.2
    Contact: VERA@aedesdatastandaarden.nl
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Optional, Union
from pydantic import BaseModel, Field, StrictFloat, StrictInt, StrictStr, conlist
from woningwaardering.vera.bvg.models.referentiedata import Referentiedata

class EenhedenEenheidVoorwaarden(BaseModel):
    """
    EenhedenEenheidVoorwaarden
    """
    id: Optional[StrictStr] = Field(None, description="De primaire sleutel van het gegeven in het bronsysteem. Je verstuurt een entiteit altijd met het eigen id. Id kan leeg zijn.")
    id_extern: Optional[StrictStr] = Field(None, alias="idExtern", description="De primaire sleutel van het gegeven in het doelsysteem. Deze idExtern wisselt om met id afhankelijk van de richting van de gegevensuitwisseling.")
    id_gegevensbeheerder: Optional[StrictStr] = Field(None, alias="idGegevensbeheerder", description="De primaire sleutel van het gegeven van de gegevensbeheerder. Bijv. de overheid of andere standaarden.")
    id_organisatie: Optional[StrictStr] = Field(None, alias="idOrganisatie", description="Dit verwijst naar de organisatie die verantwoordelijk is voor het gegeven. Horende bij de idExtern.")
    id_administratie: Optional[StrictStr] = Field(None, alias="idAdministratie", description="Dit verwijst naar de administratie waar het gegeven onderdeel van is. Horende bij de idExtern.")
    code: Optional[StrictStr] = Field(None, description="De unieke code (Bijvoorbeeld om te tonen of te zoeken)")
    maximum_aantal_personen: Optional[StrictInt] = Field(None, alias="maximumAantalPersonen", description="Het maximaal aantal personen waarvoor de eenheid geschikt is.")
    maximuminkomen: Optional[Union[StrictFloat, StrictInt]] = Field(None, description="Het maximuminkomen dat de bewoner moet hebben om in aanmerking te komen voor de eenheid.")
    maximumleeftijd: Optional[StrictInt] = Field(None, description="De maximumleeftijd waaraan de bewoner moet voldoen om in aanmerking te komen voor de eenheid.")
    maximunleeftijd: Optional[StrictInt] = Field(None, description="De maximumleeftijd waaraan de bewoner moet voldoen om in aanmerking te komen voor de eenheid. OBSOLETE")
    minimum_aantal_personen: Optional[StrictInt] = Field(None, alias="minimumAantalPersonen", description="Het minimum aantal personen waarvoor de eenheid geschikt is.")
    minimuminkomen: Optional[Union[StrictFloat, StrictInt]] = Field(None, description="Het minimuminkomen dat de bewoner moet hebben om in aanmerking te komen voor de eenheid.")
    minimumleeftijd: Optional[StrictInt] = Field(None, description="De minimumleeftijd waaraan de bewoner moet voldoen om in aanmerking te komen voor de eenheid.")
    selectiecriteria: Optional[conlist(Referentiedata)] = Field(None, description="De criteria waaraan men moet voldoen om in aanmerking te komen voor deze eenheid. Referentiedatasoort SELECTIECRITERIA.")
    voorrangscriteria: Optional[conlist(Referentiedata)] = Field(None, description="De criteria waaraan men moet voldoen om voorrang te krijgen voor deze eenheid. Referentiedatasoort VOORRANGSCRITERIA.")
    __properties = ["id", "idExtern", "idGegevensbeheerder", "idOrganisatie", "idAdministratie", "code", "maximumAantalPersonen", "maximuminkomen", "maximumleeftijd", "maximunleeftijd", "minimumAantalPersonen", "minimuminkomen", "minimumleeftijd", "selectiecriteria", "voorrangscriteria"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> EenhedenEenheidVoorwaarden:
        """Create an instance of EenhedenEenheidVoorwaarden from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in selectiecriteria (list)
        _items = []
        if self.selectiecriteria:
            for _item in self.selectiecriteria:
                if _item:
                    _items.append(_item.to_dict())
            _dict['selectiecriteria'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in voorrangscriteria (list)
        _items = []
        if self.voorrangscriteria:
            for _item in self.voorrangscriteria:
                if _item:
                    _items.append(_item.to_dict())
            _dict['voorrangscriteria'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> EenhedenEenheidVoorwaarden:
        """Create an instance of EenhedenEenheidVoorwaarden from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return EenhedenEenheidVoorwaarden.parse_obj(obj)

        _obj = EenhedenEenheidVoorwaarden.parse_obj({
            "id": obj.get("id"),
            "id_extern": obj.get("idExtern"),
            "id_gegevensbeheerder": obj.get("idGegevensbeheerder"),
            "id_organisatie": obj.get("idOrganisatie"),
            "id_administratie": obj.get("idAdministratie"),
            "code": obj.get("code"),
            "maximum_aantal_personen": obj.get("maximumAantalPersonen"),
            "maximuminkomen": obj.get("maximuminkomen"),
            "maximumleeftijd": obj.get("maximumleeftijd"),
            "maximunleeftijd": obj.get("maximunleeftijd"),
            "minimum_aantal_personen": obj.get("minimumAantalPersonen"),
            "minimuminkomen": obj.get("minimuminkomen"),
            "minimumleeftijd": obj.get("minimumleeftijd"),
            "selectiecriteria": [Referentiedata.from_dict(_item) for _item in obj.get("selectiecriteria")] if obj.get("selectiecriteria") is not None else None,
            "voorrangscriteria": [Referentiedata.from_dict(_item) for _item in obj.get("voorrangscriteria")] if obj.get("voorrangscriteria") is not None else None
        })
        return _obj


