# coding: utf-8

"""
    VERA-Beheer Vastgoedgegevens

    API-specificatie van ketenproces 'Beheer Vastgoedgegevens'. Deze specificatie is gebaseerd op VERA versie 4.1.4+240311.2

    The version of the OpenAPI document: 1.1.4+240311.2
    Contact: VERA@aedesdatastandaarden.nl
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import date
from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from woningwaardering.vera.bvg.models.eenheid_sleutels import EenheidSleutels
from woningwaardering.vera.bvg.models.extra_attribuut import ExtraAttribuut
from woningwaardering.vera.bvg.models.informatieobject import Informatieobject
from woningwaardering.vera.bvg.models.referentiedata import Referentiedata
from woningwaardering.vera.bvg.models.sturingslabel import Sturingslabel
from woningwaardering.vera.bvg.models.woningwaardering_resultaten_woningwaardering_groep import (
    WoningwaarderingResultatenWoningwaarderingGroep,
)
from typing import Set
from typing_extensions import Self


class WoningwaarderingResultatenWoningwaarderingResultaatbericht(BaseModel):
    """
    WoningwaarderingResultatenWoningwaarderingResultaatbericht
    """  # noqa: E501

    id: Optional[StrictStr] = Field(
        default=None,
        description="De primaire sleutel van het gegeven in het bronsysteem. Je verstuurt een entiteit altijd met het eigen id. Id kan leeg zijn.",
    )
    id_extern: Optional[StrictStr] = Field(
        default=None,
        description="De primaire sleutel van het gegeven in het doelsysteem. Deze idExtern wisselt om met id afhankelijk van de richting van de gegevensuitwisseling.",
        alias="idExtern",
    )
    id_gegevensbeheerder: Optional[StrictStr] = Field(
        default=None,
        description="De primaire sleutel van het gegeven van de gegevensbeheerder. Bijv. de overheid of andere standaarden.",
        alias="idGegevensbeheerder",
    )
    id_organisatie: Optional[StrictStr] = Field(
        default=None,
        description="Dit verwijst naar de organisatie die verantwoordelijk is voor het gegeven. Horende bij de idExtern.",
        alias="idOrganisatie",
    )
    id_administratie: Optional[StrictStr] = Field(
        default=None,
        description="Dit verwijst naar de administratie waar het gegeven onderdeel van is. Horende bij de idExtern.",
        alias="idAdministratie",
    )
    code: Optional[StrictStr] = Field(
        default=None,
        description="De unieke code (Bijvoorbeeld om te tonen of te zoeken)",
    )
    begindatum: Optional[date] = Field(
        default=None, description="De begindatum van de woningwaardering puntentotaal."
    )
    einddatum: Optional[date] = Field(
        default=None,
        description="De einddatum waarop de waarop de woningwaardering niet meer geldig is.",
    )
    eenheid: Optional[EenheidSleutels] = Field(
        default=None, description="De eenheid behorend bij de woningwaardering."
    )
    groepen: Optional[List[WoningwaarderingResultatenWoningwaarderingGroep]] = Field(
        default=None,
        description="De woningwaarderingenGroep behorend bij het woningwaardering puntentotaal.",
    )
    maximale_huur: Optional[Union[StrictFloat, StrictInt]] = Field(
        default=None,
        description="De maximaal redelijke huur in euro's die geregistreerd staat bij de eenheid. De maximale huur is de huurprijs die gevraagd kan worden voor de eenheid op basis van de woningwaarderingspunten.",
        alias="maximaleHuur",
    )
    opslagpercentage: Optional[Union[StrictFloat, StrictInt]] = Field(
        default=None,
        description="Het percentage dat boven de maximale huurprijs op basis van punten mag worden gerekend. Bijvoorbeeld bij specifieke monumenten binnen stads of dorpsgezichten van voor 1945 waarbij de corporatie extra onderhoud pleegt aan het monument.",
    )
    punten: Optional[Union[StrictFloat, StrictInt]] = Field(
        default=None,
        description="Het aantal woningwaarderingsstelsel punten dat is toegekend.",
    )
    stelsel: Optional[Referentiedata] = Field(
        default=None,
        description="Het woningwaardering stelsel geeft aan welk puntensysteem voor de eenheid van toepassing is: het puntensysteem voor zelfstandige woonruimten, het puntensysteem voor onzelfstandige woonruimten, of het puntensysteem voor woonwagens en standplaatsen. Referentiedatasoort WONINGWAARDERINGSTELSEL.",
    )
    extra_attributen: Optional[List[ExtraAttribuut]] = Field(
        default=None,
        description="Mogelijkheid om het bericht uit te breiden met attributen die nog niet in het logisch datamodel beschikbaar zijn",
        alias="extra-attributen",
    )
    informatieobjecten: Optional[List[Informatieobject]] = Field(
        default=None,
        description="Mogelijkheid om het bericht uit te breiden met documentatie. De beschrijving kan de inhoud van een notitie of memo zijn",
    )
    sturingslabels: Optional[List[Sturingslabel]] = Field(
        default=None,
        description="Mogelijkheid om het bericht uit te breiden met sturingslabels",
    )
    __properties: ClassVar[List[str]] = [
        "id",
        "idExtern",
        "idGegevensbeheerder",
        "idOrganisatie",
        "idAdministratie",
        "code",
        "begindatum",
        "einddatum",
        "eenheid",
        "groepen",
        "maximaleHuur",
        "opslagpercentage",
        "punten",
        "stelsel",
        "extra-attributen",
        "informatieobjecten",
        "sturingslabels",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of WoningwaarderingResultatenWoningwaarderingResultaatbericht from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of eenheid
        if self.eenheid:
            _dict["eenheid"] = self.eenheid.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in groepen (list)
        _groepen_items = []
        if self.groepen:
            for _groepen_item in self.groepen:
                if _groepen_item:
                    _groepen_items.append(_groepen_item.to_dict())
            _dict["groepen"] = _groepen_items
        # override the default output from pydantic by calling `to_dict()` of stelsel
        if self.stelsel:
            _dict["stelsel"] = self.stelsel.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in extra_attributen (list)
        _extra_attributen_items = []
        if self.extra_attributen:
            for _extra_attributen_item in self.extra_attributen:
                if _extra_attributen_item:
                    _extra_attributen_items.append(_extra_attributen_item.to_dict())
            _dict["extra-attributen"] = _extra_attributen_items
        # override the default output from pydantic by calling `to_dict()` of each item in informatieobjecten (list)
        _informatieobjecten_items = []
        if self.informatieobjecten:
            for _informatieobjecten_item in self.informatieobjecten:
                if _informatieobjecten_item:
                    _informatieobjecten_items.append(_informatieobjecten_item.to_dict())
            _dict["informatieobjecten"] = _informatieobjecten_items
        # override the default output from pydantic by calling `to_dict()` of each item in sturingslabels (list)
        _sturingslabels_items = []
        if self.sturingslabels:
            for _sturingslabels_item in self.sturingslabels:
                if _sturingslabels_item:
                    _sturingslabels_items.append(_sturingslabels_item.to_dict())
            _dict["sturingslabels"] = _sturingslabels_items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of WoningwaarderingResultatenWoningwaarderingResultaatbericht from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "id": obj.get("id"),
                "idExtern": obj.get("idExtern"),
                "idGegevensbeheerder": obj.get("idGegevensbeheerder"),
                "idOrganisatie": obj.get("idOrganisatie"),
                "idAdministratie": obj.get("idAdministratie"),
                "code": obj.get("code"),
                "begindatum": obj.get("begindatum"),
                "einddatum": obj.get("einddatum"),
                "eenheid": EenheidSleutels.from_dict(obj["eenheid"])
                if obj.get("eenheid") is not None
                else None,
                "groepen": [
                    WoningwaarderingResultatenWoningwaarderingGroep.from_dict(_item)
                    for _item in obj["groepen"]
                ]
                if obj.get("groepen") is not None
                else None,
                "maximaleHuur": obj.get("maximaleHuur"),
                "opslagpercentage": obj.get("opslagpercentage"),
                "punten": obj.get("punten"),
                "stelsel": Referentiedata.from_dict(obj["stelsel"])
                if obj.get("stelsel") is not None
                else None,
                "extra-attributen": [
                    ExtraAttribuut.from_dict(_item) for _item in obj["extra-attributen"]
                ]
                if obj.get("extra-attributen") is not None
                else None,
                "informatieobjecten": [
                    Informatieobject.from_dict(_item)
                    for _item in obj["informatieobjecten"]
                ]
                if obj.get("informatieobjecten") is not None
                else None,
                "sturingslabels": [
                    Sturingslabel.from_dict(_item) for _item in obj["sturingslabels"]
                ]
                if obj.get("sturingslabels") is not None
                else None,
            }
        )
        return _obj
